"""Metaphor Enrichment Spike — Phase 2 runner (cohort scale-up).

200 anchor topics × Haiku-only × 2 prompts ≈ 400 LLM calls. Uses the
exact same Sonnet-as-prompt-engineer apt/inapt templates baked in
Phase 1b — only the topic source differs.

Topic source: ``data-pipeline/scripts/spike_2_topics.json`` (built by
``curate_spike_2_topics.py``). 20 hand-curated spine topics from
Phase 1b + 180 sampled across three concreteness bands.

Phase 2 produces the **evaluation cohort** for M05 calibration close-
out, plus the per-`inapt_reason_type` discrimination breakdown at
real scale. The follow-up metric correction (end-to-end aptness
against the full cohort, not just scored pairs) and concept
lemmatisation are deliberately deferred — see
``docs/inbox/2026-05-25-metaphor-spike-findings.md``.

Usage::

    python data-pipeline/scripts/metaphor_spike_2.py \\
        --db data-pipeline/output/lexicon_v2.db \\
        --topics data-pipeline/scripts/spike_2_topics.json \\
        --output-dir data-pipeline/output

Outputs (written to --output-dir; <TS> = YYYYMMDDTHHMMSS)::

    metaphor_spike_apt_phase2_<TS>.jsonl
    metaphor_spike_inapt_phase2_<TS>.jsonl
    metaphor_spike_scores_phase2_<TS>.jsonl
    metaphor_spike_scoring_phase2_<TS>.md
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "lib"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import argparse
import json
import logging
import sqlite3
from contextlib import closing
from datetime import datetime

from claude_client import prompt_json, ClaudeError
from metaphor_spike_1a import (
    AptValidation,
    ConceptSnapResult,
    InaptValidation,
    MODEL_HAIKU,
    PRODUCTION_CASCADE_CONFIG,
    check_concept_snap_rate,
    compute_gate_metrics,
    validate_apt_response,
    validate_inapt_response,
    write_jsonl_line,
)
from metaphor_spike_1b import (
    _score_apt_local,
    build_apt_prompt,
    build_inapt_prompt,
    compute_discrimination,
    score_inapt_vehicles,
)

log = logging.getLogger(__name__)


def _load_topics(path: Path) -> list[dict[str, str]]:
    """Read the curator-produced topics JSON into a flat list."""
    if not path.exists():
        raise FileNotFoundError(
            f"Topics file missing: {path}. Run curate_spike_2_topics.py first."
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    topics = data.get("topics", [])
    if not topics:
        raise ValueError(f"Topics file has no topics: {path}")
    out: list[dict[str, str]] = []
    for t in topics:
        word = t.get("word")
        gloss = t.get("gloss")
        if not word or not gloss:
            log.warning("skipping malformed topic: %r", t)
            continue
        out.append({"word": word, "gloss": gloss})
    return out


def write_report(
    path: Path,
    topics: list[dict[str, str]],
    apt_metrics,
    inapt_metrics,
    apt_scored,
    inapt_scored,
    concept_violations,
    unsnapped_concepts,
    discrimination,
) -> None:
    """Phase 2 report — same structure as Phase 1b, larger tables."""
    def _status_counts(rows):
        c: dict[str, int] = {}
        for r in rows:
            c[r.cascade_status] = c.get(r.cascade_status, 0) + 1
        return c

    apt_counts = _status_counts(apt_scored)
    inapt_counts = _status_counts(inapt_scored)

    lines: list[str] = [
        "# Metaphor Spike Phase 2 — Cohort Discrimination Report",
        "",
        f"Generated by `metaphor_spike_2.py`. Topics: {len(topics)} · "
        f"Model: {MODEL_HAIKU} · Prompt types: 2 · Total calls: "
        f"{len(topics) * 2}",
        "",
        "Architecture: Sonnet-as-prompt-engineer. The Phase 1b gold "
        "few-shot examples (love, knowledge, fear) are baked into "
        "Haiku's apt/inapt templates; Haiku then drafts every Phase 2 "
        "response. See `docs/inbox/2026-05-25-metaphor-spike-findings.md` "
        "for the cross-phase narrative.",
        "",
        "## Format Gates",
        "",
        "### Apt Prompt",
        "",
        "| Model | Calls | Parse OK | Schema OK | Single-word % | Snap rate |",
        "|-------|-------|----------|-----------|---------------|-----------|",
        f"| {apt_metrics.model} | {apt_metrics.n_calls} | "
        f"{apt_metrics.parse_ok_rate:.0%} | {apt_metrics.schema_ok_rate:.0%} | "
        f"{apt_metrics.single_word_rate:.0%} | {apt_metrics.snap_rate:.0%} |",
        "",
        "### Inapt Prompt",
        "",
        "| Model | Calls | Parse OK | Schema OK |",
        "|-------|-------|----------|-----------|",
        f"| {inapt_metrics.model} | {inapt_metrics.n_calls} | "
        f"{inapt_metrics.parse_ok_rate:.0%} | {inapt_metrics.schema_ok_rate:.0%} |",
        "",
        "## Cascade Score Summary",
        "",
        "| Cohort | Scored | Gate dropped | Unresolved | Missing concreteness | No properties |",
        "|--------|--------|--------------|------------|----------------------|---------------|",
        f"| apt   | {apt_counts.get('scored', 0)} | {apt_counts.get('gate_dropped', 0)} | "
        f"{apt_counts.get('unresolved', 0)} | {apt_counts.get('missing_concreteness', 0)} | "
        f"{apt_counts.get('no_properties', 0)} |",
        f"| inapt | {inapt_counts.get('scored', 0)} | {inapt_counts.get('gate_dropped', 0)} | "
        f"{inapt_counts.get('unresolved', 0)} | {inapt_counts.get('missing_concreteness', 0)} | "
        f"{inapt_counts.get('no_properties', 0)} |",
        "",
        "## Discrimination Metrics (scored-pair only)",
        "",
        "These metrics use the **legacy scored-pair denominator** that "
        "Phase 1b flagged as misleading. See FU-1 in the findings doc. "
        "The end-to-end discrimination (including gate-dropped vehicles) "
        "is computed below.",
        "",
        f"- Mean apt score (scored only): **{discrimination.mean_apt_score:.4f}** "
        f"(n={discrimination.n_apt_scored})",
        f"- Mean inapt score (scored only): **{discrimination.mean_inapt_score:.4f}** "
        f"(n={discrimination.n_inapt_scored})",
        f"- **Separation score = {discrimination.separation_score:+.4f}**",
        f"- Median threshold (apt ∪ inapt): {discrimination.median_threshold:.4f}",
        f"- Aptness rate (median split, scored only): {discrimination.aptness_rate:.0%}",
        f"- False positive rate (scored only):       {discrimination.false_positive_rate:.0%}",
        "",
    ]

    # End-to-end aptness — FU-1 preview, computed inline against the
    # full vehicle counts so M05 calibration has a working signal.
    n_apt_total = len(apt_scored)
    n_inapt_total = len(inapt_scored)
    n_apt_above = sum(
        1 for sv in apt_scored
        if sv.cascade_status == "scored"
        and sv.final_score is not None
        and sv.final_score > discrimination.median_threshold
    )
    n_inapt_above = sum(
        1 for sv in inapt_scored
        if sv.cascade_status == "scored"
        and sv.final_score is not None
        and sv.final_score > discrimination.median_threshold
    )
    e2e_apt = n_apt_above / n_apt_total if n_apt_total else 0.0
    e2e_inapt = n_inapt_above / n_inapt_total if n_inapt_total else 0.0
    e2e_ratio = (e2e_apt / e2e_inapt) if e2e_inapt else float("inf")

    lines += [
        "## End-to-End Aptness (FU-1 preview)",
        "",
        "Counts a vehicle as 'promoted' only if it (a) survived the "
        "concreteness gate, (b) scored, and (c) scored above the median "
        "threshold. Denominator is the **full cohort** including gate-"
        "dropped, missing-concreteness, and no-properties — these all "
        "count as 'system declined to promote'.",
        "",
        f"- n_apt_above_median   / n_apt_total   = {n_apt_above}/{n_apt_total} = **{e2e_apt:.1%}**",
        f"- n_inapt_above_median / n_inapt_total = {n_inapt_above}/{n_inapt_total} = **{e2e_inapt:.1%}**",
        f"- System discrimination ratio: **{e2e_ratio:.2f}×**",
        "",
        "## Per-`inapt_reason_type` Discrimination",
        "",
        "| Reason | n_total | n_scored | Mean score | Discriminated rate | Gate-pass rate |",
        "|--------|---------|----------|------------|--------------------|----------------|",
    ]
    for reason, b in sorted(discrimination.per_reason_breakdown.items()):
        lines.append(
            f"| {reason} | {b['n_total']} | {b['n_scored']} | "
            f"{b['mean_score']:.4f} | {b['discriminated_rate']:.0%} | "
            f"{b['gate_pass_rate']:.0%} |"
        )
    lines.append("")

    if concept_violations:
        # Cap at 50 to keep the report digestible — Phase 2 may have many.
        capped = sorted(set(concept_violations))[:50]
        lines += [
            "## Multi-word Concept Violations (first 50)",
            "",
            f"Total unique violations: {len(set(concept_violations))}",
            "",
        ]
        for cv in capped:
            lines.append(f"- `{cv}`")
        lines.append("")

    if unsnapped_concepts:
        capped = sorted(set(unsnapped_concepts))[:80]
        lines += [
            "## Unsnapped Concepts (first 80)",
            "",
            f"Total unique unsnapped concepts: {len(set(unsnapped_concepts))}",
            "",
        ]
        for uc in capped:
            lines.append(f"- `{uc}`")
        lines.append("")

    lines += [
        "## Gate Decision (Phase 2 → M05 calibration close-out)",
        "",
        "- [ ] JSON parseability ≥80%: **PASS / FAIL**",
        "- [ ] Schema compliance ≥80%: **PASS / FAIL**",
        "- [ ] Single-word concept compliance ≥90%: **PASS / FAIL**",
        "- [ ] Concept snap-rate ≥80%: **PASS / FAIL**",
        "- [ ] End-to-end discrimination ratio > 1.5×: **PASS / FAIL**",
        "- [ ] Operator eyeball acceptable: **PASS / FAIL**",
        "",
        "**Overall Phase 2 verdict:** PASS / FAIL",
        "",
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    log.info("wrote report to %s", path)


def run_spike(
    db_path: Path,
    topics_path: Path,
    output_dir: Path,
    log_every: int = 10,
) -> None:
    """Run Phase 2: ~400 Haiku calls + cascade scoring + report."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    if not db_path.exists():
        raise FileNotFoundError(f"DB not found: {db_path}")
    topics = _load_topics(topics_path)
    log.info("loaded %d topics from %s", len(topics), topics_path)

    with closing(sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)) as conn:
        run_ts = datetime.now().strftime("%Y%m%dT%H%M%S")
        log.info("run_timestamp=%s", run_ts)

        output_dir.mkdir(parents=True, exist_ok=True)

        def _path(stem: str, ext: str = "jsonl") -> Path:
            return output_dir / f"metaphor_spike_{stem}_phase2_{run_ts}.{ext}"

        apt_path = _path("apt")
        inapt_path = _path("inapt")
        scores_path = _path("scores")
        report_path = _path("scoring", ext="md")

        for p in (apt_path, inapt_path, scores_path, report_path):
            if p.exists():
                raise FileExistsError(
                    f"Output file already exists: {p} — same-second re-run. "
                    f"Wait one second and re-invoke."
                )

        apt_validations: list[AptValidation] = []
        inapt_validations: list[InaptValidation] = []
        apt_scored_all = []
        inapt_scored_all = []
        concept_violations: list[str] = []
        apt_concepts: list[str] = []

        for idx, topic in enumerate(topics):
            word = topic["word"]
            gloss = topic["gloss"]
            if idx % log_every == 0:
                log.info("[%d/%d] topic=%s", idx + 1, len(topics), word)

            # --- Apt call ---------------------------------------------------
            apt_prompt = build_apt_prompt(word, gloss)
            try:
                raw_apt = prompt_json(apt_prompt, model=MODEL_HAIKU, expect=dict)
                raw_apt["_gloss"] = gloss
                write_jsonl_line(apt_path, raw_apt)
                v_apt = validate_apt_response(raw_apt)
            except ClaudeError as e:
                log.warning("apt call failed topic=%s: %s", word, e)
                raw_apt = {"topic": word, "metaphors": [], "_error": str(e)}
                write_jsonl_line(apt_path, raw_apt)
                v_apt = AptValidation(
                    schema_ok=False, n_vehicles=0, n_concepts=0,
                    n_single_word_concepts=0, concept_violations=[],
                    schema_errors=[f"parse_failure: {e}"],
                )

            apt_validations.append(v_apt)
            concept_violations.extend(v_apt.concept_violations)
            apt_concepts.extend(
                sf["concept"]
                for m_entry in raw_apt.get("metaphors", [])
                if isinstance(m_entry, dict)
                for sf in m_entry.get("shared_features", [])
                if isinstance(sf, dict) and isinstance(sf.get("concept"), str)
            )

            if v_apt.schema_ok:
                scored = _score_apt_local(conn, raw_apt, PRODUCTION_CASCADE_CONFIG)
                apt_scored_all.extend(scored)
                for sv in scored:
                    write_jsonl_line(scores_path, {
                        "cohort": "apt",
                        "topic": sv.topic,
                        "vehicle": sv.vehicle,
                        "synset_topic": sv.synset_topic,
                        "synset_vehicle": sv.synset_vehicle,
                        "cascade_status": sv.cascade_status,
                        "final_score": sv.final_score,
                        "gate_passed": sv.gate_passed,
                    })

            # --- Inapt call -------------------------------------------------
            inapt_prompt = build_inapt_prompt(word, gloss)
            try:
                raw_inapt = prompt_json(inapt_prompt, model=MODEL_HAIKU, expect=dict)
                raw_inapt["_gloss"] = gloss
                write_jsonl_line(inapt_path, raw_inapt)
                v_inapt = validate_inapt_response(raw_inapt)
            except ClaudeError as e:
                log.warning("inapt call failed topic=%s: %s", word, e)
                raw_inapt = {"topic": word, "inapt_metaphors": [], "_error": str(e)}
                write_jsonl_line(inapt_path, raw_inapt)
                v_inapt = InaptValidation(
                    schema_ok=False, n_vehicles=0,
                    schema_errors=[f"parse_failure: {e}"],
                )
            inapt_validations.append(v_inapt)

            if v_inapt.schema_ok:
                inapt_scored = score_inapt_vehicles(
                    conn, raw_inapt, PRODUCTION_CASCADE_CONFIG
                )
                inapt_scored_all.extend(inapt_scored)
                for sv in inapt_scored:
                    write_jsonl_line(scores_path, {
                        "cohort": "inapt",
                        "topic": sv.topic,
                        "vehicle": sv.vehicle,
                        "inapt_reason_type": sv.inapt_reason_type,
                        "synset_topic": sv.synset_topic,
                        "synset_vehicle": sv.synset_vehicle,
                        "cascade_status": sv.cascade_status,
                        "final_score": sv.final_score,
                        "gate_passed": sv.gate_passed,
                    })

        snap = check_concept_snap_rate(conn, apt_concepts)
        apt_metrics = compute_gate_metrics(
            apt_validations, snap, model=MODEL_HAIKU, prompt_type="apt"
        )
        inapt_metrics = compute_gate_metrics(
            [
                AptValidation(
                    schema_ok=v.schema_ok, n_vehicles=v.n_vehicles,
                    n_concepts=0, n_single_word_concepts=0,
                    concept_violations=[], schema_errors=v.schema_errors,
                )
                for v in inapt_validations
            ],
            ConceptSnapResult(n_concepts=0, n_snapped=0, snap_rate=0.0, unsnapped=[]),
            model=MODEL_HAIKU, prompt_type="inapt",
        )

        discrimination = compute_discrimination(apt_scored_all, inapt_scored_all)

    write_report(
        report_path, topics, apt_metrics, inapt_metrics,
        apt_scored_all, inapt_scored_all,
        concept_violations, snap.unsnapped, discrimination,
    )

    print("\n=== Phase 2 Gate-Check Summary ===")
    print(
        f"  apt    parse={apt_metrics.parse_ok_rate:.0%}  "
        f"schema={apt_metrics.schema_ok_rate:.0%}  "
        f"single-word={apt_metrics.single_word_rate:.0%}  "
        f"snap={apt_metrics.snap_rate:.0%}"
    )
    print(
        f"  inapt  parse={inapt_metrics.parse_ok_rate:.0%}  "
        f"schema={inapt_metrics.schema_ok_rate:.0%}"
    )
    print(
        f"  separation={discrimination.separation_score:+.4f}  "
        f"aptness_rate={discrimination.aptness_rate:.0%}  "
        f"fp_rate={discrimination.false_positive_rate:.0%}"
    )
    print(f"\nReport: {report_path}")
    print(f"Scores: {scores_path}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--db", type=Path,
        default=Path(__file__).resolve().parent.parent / "output" / "lexicon_v2.db",
    )
    ap.add_argument(
        "--topics", type=Path,
        default=Path(__file__).resolve().parent / "spike_2_topics.json",
        help="Path to curator-produced topics JSON (default: alongside this script).",
    )
    ap.add_argument(
        "--output-dir", type=Path,
        default=Path(__file__).resolve().parent.parent / "output",
    )
    ap.add_argument(
        "--log-every", type=int, default=10,
        help="Print a progress line every N topics (default: 10).",
    )
    args = ap.parse_args(argv)
    run_spike(args.db, args.topics, args.output_dir, log_every=args.log_every)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
